# -*- coding: utf-8 -*-
LIBRARY_PATH = '/Library/'
MAIN_WINDOW_GEOMETRY = '1478x395'
MAIN_WINDOW_TITLE = 'База данных видеокарт NVIDIA'
MAIN_WINDOW_ICO = '../Graphics/icon.ico'
BACKGROUND_IMAGE = '../Graphics/background.png'
BUTTON_WIDTH = 13
BUTTON_ACTIVE_FOREGROUND = '#1A1918'
FOREGROUNG_COLOUR = '#76b900'
BACKGROUND_COLOUR = '#1A1918'
TEXT_OPTIONS = ('Roboto', 12, 'bold')
READ_ADDRESS = '../Data/bd.csv'
DATA_SAVE_ADDRESS = '../Data/data'
BAR_PLOT_ADDRESS = '../Output/Столбчатая диаграмма.png'
HIST_PLOT_ADDRESS = '../Output/Гистограмма.png'
BOX_PLOT_ADDRESS = '../Output/Диаграмма Бокса-Вискерса.png'
SCATTER_PLOT_ADDRESS = '../Output/Диаграмма рассеивания.png'
TEXT_REPORT_ADDRESS = '../Output/output.txt'
ERROR_MESSAGE = 'Ошибка'
